import type {
	IExecuteSingleFunctions,
	IHttpRequestOptions,
	IN8nHttpFullResponse,
	INodeExecutionData,
} from 'n8n-workflow';

/**
 * Attach a binary property as a multipart upload.
 *
 * Declarative nodes cannot express multipart in the routing block, but a
 * preSend hook runs with the full execute context, which is enough to read
 * the binary buffer and rewrite the request. Any plain fields already in the
 * body (folder ids, flags) travel along as ordinary form fields.
 *
 * The body has to be a real `FormData` instance: the routing engine sends
 * requests through n8n's axios-based client, which only produces a multipart
 * body for spec-compliant form data. A plain object shaped like the old
 * `request` library's `formData` would be JSON-encoded, buffer and all. The
 * global `FormData` and `Blob` are used so that the package needs no runtime
 * dependency for this.
 */
export async function uploadBinary(
	this: IExecuteSingleFunctions,
	requestOptions: IHttpRequestOptions,
): Promise<IHttpRequestOptions> {
	const binaryProperty = this.getNodeParameter('binaryPropertyName') as string;
	const binaryData = this.helpers.assertBinaryData(binaryProperty);
	const buffer = await this.helpers.getBinaryDataBuffer(binaryProperty);

	const fields: Record<string, unknown> =
		typeof requestOptions.body === 'object' && requestOptions.body !== null
			? (requestOptions.body as Record<string, unknown>)
			: {};

	const form = new FormData();

	for (const [name, value] of Object.entries(fields)) {
		// An optional field the expression resolved to nothing must not travel
		// as the string "undefined" — the API would reject it as a bad ULID.
		if (value === undefined || value === null || value === '') {
			continue;
		}
		form.append(name, typeof value === 'string' ? value : String(value));
	}

	form.append(
		'file',
		new Blob([new Uint8Array(buffer)], { type: binaryData.mimeType }),
		binaryData.fileName ?? 'upload',
	);

	requestOptions.body = form as unknown as IHttpRequestOptions['body'];

	// Content-Type has to go, not be overwritten: the multipart boundary is
	// generated by the request layer and only lands in the header when we
	// leave the field alone. Worse, a lingering application/json makes axios
	// re-encode the form as JSON.
	if (requestOptions.headers !== undefined) {
		delete requestOptions.headers['Content-Type'];
	}
	requestOptions.json = false;

	return requestOptions;
}

/**
 * Turn a binary response into a binary property on the output item.
 *
 * Requires the operation to request the body as `arraybuffer` with
 * `json: false` and `returnFullResponse: true` — without those the response
 * is parsed as text and a PDF arrives as mojibake.
 */
export async function downloadBinary(
	this: IExecuteSingleFunctions,
	_items: INodeExecutionData[],
	responseData: IN8nHttpFullResponse,
): Promise<INodeExecutionData[]> {
	const headers = responseData.headers as Record<string, string | undefined>;
	const fileName = extractFileName(headers['content-disposition']);
	const body = responseData.body as Buffer | ArrayBuffer;
	const buffer = Buffer.isBuffer(body) ? body : Buffer.from(body);
	const binary = await this.helpers.prepareBinaryData(buffer, fileName, headers['content-type']);

	return [
		{
			json: { fileName, mimeType: binary.mimeType, fileSize: binary.fileSize },
			binary: { data: binary },
		},
	];
}

export function extractFileName(contentDisposition: string | undefined): string {
	if (contentDisposition === undefined) {
		return 'download';
	}
	// Prefer filename*= (RFC 5987, percent-encoded UTF-8) over filename=:
	// document titles routinely carry umlauts, and the plain field is the
	// ASCII-mangled fallback the RFC tells senders to provide.
	const encoded = /filename\*=UTF-8''([^;]+)/i.exec(contentDisposition);
	if (encoded !== null) {
		try {
			return decodeURIComponent(encoded[1]);
		} catch {
			// fall through to the plain field
		}
	}
	const plain = /filename="?([^";]+)"?/i.exec(contentDisposition);
	return plain !== null ? plain[1] : 'download';
}
