import type {
	IExecuteSingleFunctions,
	IHttpRequestOptions,
	IN8nHttpFullResponse,
	INodeExecutionData,
} from 'n8n-workflow';

/**
 * Attach a binary property as a multipart upload.
 *
 * Declarative nodes cannot express multipart in the routing block, but a
 * preSend hook runs with the full execute context, which is enough to read
 * the binary buffer and rewrite the request. Any plain fields already in the
 * body (folder ids, titles) travel along as ordinary form fields.
 */
export async function uploadBinary(
	this: IExecuteSingleFunctions,
	requestOptions: IHttpRequestOptions,
): Promise<IHttpRequestOptions> {
	const binaryProperty = this.getNodeParameter('binaryPropertyName') as string;
	const binaryData = this.helpers.assertBinaryData(binaryProperty);
	const buffer = await this.helpers.getBinaryDataBuffer(binaryProperty);

	const fields: Record<string, unknown> =
		typeof requestOptions.body === 'object' && requestOptions.body !== null
			? { ...(requestOptions.body as Record<string, unknown>) }
			: {};

	requestOptions.body = {
		...fields,
		file: {
			value: buffer,
			options: {
				filename: binaryData.fileName ?? 'upload',
				contentType: binaryData.mimeType,
			},
		},
	};

	// Content-Type has to go, not be overwritten: the multipart boundary is
	// generated by the request layer and only lands in the header when we
	// leave the field alone.
	if (requestOptions.headers !== undefined) {
		delete requestOptions.headers['Content-Type'];
	}
	requestOptions.json = false;

	return requestOptions;
}

/**
 * Turn a binary response into a binary property on the output item.
 *
 * Requires the operation to request the body as `arraybuffer` with
 * `json: false` and `returnFullResponse: true` — without those the response
 * is parsed as text and a PDF arrives as mojibake.
 */
export async function downloadBinary(
	this: IExecuteSingleFunctions,
	_items: INodeExecutionData[],
	responseData: IN8nHttpFullResponse,
): Promise<INodeExecutionData[]> {
	const headers = responseData.headers as Record<string, string | undefined>;
	const fileName = extractFileName(headers['content-disposition']);
	const body = responseData.body as Buffer | ArrayBuffer;
	const buffer = Buffer.isBuffer(body) ? body : Buffer.from(body);
	const binary = await this.helpers.prepareBinaryData(buffer, fileName, headers['content-type']);

	return [
		{
			json: { fileName, mimeType: binary.mimeType, fileSize: binary.fileSize },
			binary: { data: binary },
		},
	];
}

export function extractFileName(contentDisposition: string | undefined): string {
	if (contentDisposition === undefined) {
		return 'download';
	}
	// Prefer filename*= (RFC 5987, percent-encoded UTF-8) over filename=:
	// document titles routinely carry umlauts, and the plain field is the
	// ASCII-mangled fallback the RFC tells senders to provide.
	const encoded = /filename\*=UTF-8''([^;]+)/i.exec(contentDisposition);
	if (encoded !== null) {
		try {
			return decodeURIComponent(encoded[1]);
		} catch {
			// fall through to the plain field
		}
	}
	const plain = /filename="?([^";]+)"?/i.exec(contentDisposition);
	return plain !== null ? plain[1] : 'download';
}
